title: Registers
baseurl: "/www.openregister.org" # the subpath of your site, e.g. /blog
data_dir: /tmp/jekyll_data

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor

# tag_page_layout: tag_page
# tag_page_dir: tag
# tag_permalink_style: pretty

collections:
  pattern:
    output: true

defaults:
  - scope:
      path: ""
      type: pattern
    values:
      layout: pattern_single

gems:
  - jekyll-redirect-from

jekyll_get:
  - data: discovery_register
    json: 'https://register.discovery.openregister.org/records.json?page-size=5000'
    cache: true
  - data: alpha_register
    json: 'https://register.alpha.openregister.org/records.json?page-size=5000'
    cache: true
  - data: beta_register
    json: 'https://register.beta.openregister.org/records.json?page-size=5000'
    cache: true
