title: Registers
#baseurl: "/register-design-patterns" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor

# tag_page_layout: tag_page
# tag_page_dir: tag
# tag_permalink_style: pretty

collections:
  pattern:
    output: true

defaults:
  - scope:
      path: ""
      type: pattern
    values:
      layout: pattern_single

gems:
  - jekyll-redirect-from
